### ISSUE TITLE
Some errors in merge sort in C++

### ISSUE THREAD

**Issue by willidert** [Knackie/algorithmshacktoberfest2020#22]
Hi, this [file](https://github.com/Knackie/algorithmshacktoberfest2020/blob/d6423dd1e3d550741df7ac2e4d1142ec104a2f5f/algorithms/ar-msrt/C%2B%2B/ar-msrt.cpp) has some errors.
I can solve it but they are simple, I believe it is good to give opportunity to other people.

- [ ] [error 1](https://github.com/Knackie/algorithmshacktoberfest2020/blob/d6423dd1e3d550741df7ac2e4d1142ec104a2f5f/algorithms/ar-msrt/C%2B%2B/ar-msrt.cpp#L56)
- [ ] [error 2](https://github.com/Knackie/algorithmshacktoberfest2020/blob/d6423dd1e3d550741df7ac2e4d1142ec104a2f5f/algorithms/ar-msrt/C%2B%2B/ar-msrt.cpp#L63)

**Comment by Knackie** [comment]
Ok, i put the hacktoberfest.
Thanks for info. 
You can solve it if you want, or wait to see if someone try it
